-- 기본구조
SELECT
FROM
WHERE
GROUP BY
ORDER BY


--
-- NULL 처리하기
SELECT ANIMAL_TYPE,
       IF (NAME IS NULL, 'No name', NAME) as NAME
        , SEX_UPON_INTAKE
FROM ANIMAL_INS

--          경기도에 위치한 식품창고 목록 출력하기
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
       If(FREEZER_YN IS NULL, 'N', FREEZER_YN) as FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID

--     강원도에 위치한 생산공장 목록 출력하기
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS
FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID

--     DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME,
       DATE_FORMAT(DATETIME, '%Y-%m-%d') AS 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

--     흉부외과 또는 일반외과 의사 목록 출력하기
SELECT  DR_NAME, DR_ID, MCDP_CD,
        DATE_FORMAT(HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR
WHERE MCDP_CD = 'CS' OR MCDP_CD	= 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME

--     가격이 제일 비싼 식품의 정보 출력하기
SELECT  PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD,
        CATEGORY, PRICE
FROM FOOD_PRODUCT
Order by PRICE DESC
    limit 1

-- 이름이 없는 동물의 아이디
SELECT  ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
Order by ANIMAL_ID

--     조건에 맞는 회원수 구하기
SELECT count(USER_ID) as USERS
FROM USER_INFO
WHERE YEAR(JOINED) = '2021'
  AND 20 <= AGE AND AGE <= 29;